services:
  db:
    image: postgres:14.7
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=pguser
      - POSTGRES_PASSWORD=pgpassword
  pgadmin4:
    image: dpage/pgadmin4
    ports:
        - 8888:80
    environment:
        PGADMIN_DEFAULT_EMAIL: xxxxxx@gmail.com
        PGADMIN_DEFAULT_PASSWORD: password
    depends_on:
      - db